services:
  api:
    build: .
    ports: ["8000:8000"]
    environment:
      HF_HOME: /models/hf
      TORCH_HOME: /models/torch
      TOKENIZERS_PARALLELISM: "false"
      # マシンのvCPUに合わせて調整（例: 8vCPUなら8）
      OMP_NUM_THREADS: 10
      MKL_NUM_THREADS: 10
      # まずは高速モード（文字CTC→近似IPA）で1秒未満を目指す
      USE_PHONEME_BACKEND: "false"
      PHONEME_MODEL: facebook/wav2vec2-lv-60-espeak-cv-ft
    volumes:
      - ./data:/data
      - ./models:/models
      - ./app:/app
